import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Notifications from '@/components/Notifications'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Comfortable Shoe Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Notifications />
        <Navbar/>
        {children}
        <Footer />
        </body>
    </html>
  )
}
